# Transformation of the UCI "Online retail 2" dataset in CSV format

The main objective is to transform this UCI dataset into a CSV file with the following format <Id, Date/Order, Attribute1, Attribute2,...>.

Load the original Excel file:

In [25]:
import pandas as pd
import csv

online_retail = pd.read_excel('../Data/Raw/online retail 2/online_retail_II.xlsx', header=0, usecols=['Customer ID','InvoiceDate','Description','Quantity','Price', 'Country'], parse_dates=[4], dtype={'Customer ID': str})

Rename the "Customer id" and "InvoiceDate" columns into "Id" and "Date" (and change their order):

In [26]:
online_retail = online_retail.rename(columns={'Customer ID':'Id','InvoiceDate':'Date'})

column_names = ['Id','Date','Description','Quantity','Price', 'Country'] 
online_retail = online_retail.reindex(columns=column_names)

online_retail.head(20)

,Id,Date,Description,Quantity,Price,Country
0,13085,2009-12-01 07:45:00,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,United Kingdom
1,13085,2009-12-01 07:45:00,PINK CHERRY LIGHTS,12,6.75,United Kingdom
2,13085,2009-12-01 07:45:00,WHITE CHERRY LIGHTS,12,6.75,United Kingdom
3,13085,2009-12-01 07:45:00,"RECORD FRAME 7"" SINGLE SIZE",48,2.10,United Kingdom
4,13085,2009-12-01 07:45:00,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,United Kingdom
5,13085,2009-12-01 07:45:00,PINK DOUGHNUT TRINKET POT,24,1.65,United Kingdom
6,13085,2009-12-01 07:45:00,SAVE THE PLANET MUG,24,1.25,United Kingdom
7,13085,2009-12-01 07:45:00,FANCY FONT HOME SWEET HOME DOORMAT,10,5.95,United Kingdom
8,13085,2009-12-01 07:46:00,CAT BOWL,12,2.55,United Kingdom
9,13085,2009-12-01 07:46:00,"DOG BOWL , CHASING BALL DESIGN",12,3.75,United Kingdom
10,13085,2009-12-01 07:46:00,HEART MEASURING SPOONS LARGE,24,1.65,United Kingdom
11,13085,2009-12-01 07:46:00,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2.55,United Kingdom
12,13078,2009-12-01 09:06:00,DOOR MAT BLACK FLOCK,10,5.95,United Kingdom
13,13078,2009-12-01 09:06:00,LOVE BUILDING BLOCK WORD,18,5.45,United Kingdom
14,13078,2009-12-01 09:06:00,HOME BUILDING BLOCK WORD,3,5.95,United Kingdom
15,13078,2009-12-01 09:06:00,ASSORTED COLOUR BIRD ORNAMENT,16,1.69,United Kingdom
16,13078,2009-12-01 09:06:00,PEACE WOODEN BLOCK LETTERS,3,6.95,United Kingdom
17,13078,2009-12-01 09:06:00,CHRISTMAS CRAFT WHITE FAIRY,12,1.45,United Kingdom
18,13078,2009-12-01 09:06:00,HEART IVORY TRELLIS LARGE,12,1.65,United Kingdom
19,13078,2009-12-01 09:06:00,HEART FILIGREE DOVE LARGE,12,1.65,United Kingdom

Delete "," in the values of the "Description" column:

In [27]:

online_retail['Description'] = online_retail['Description'].str.replace(',','-')
online_retail.head(20)

,Id,Date,Description,Quantity,Price,Country
0,13085,2009-12-01 07:45:00,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,United Kingdom
1,13085,2009-12-01 07:45:00,PINK CHERRY LIGHTS,12,6.75,United Kingdom
2,13085,2009-12-01 07:45:00,WHITE CHERRY LIGHTS,12,6.75,United Kingdom
3,13085,2009-12-01 07:45:00,RECORD FRAME 7inch SINGLE SIZE,48,2.10,United Kingdom
4,13085,2009-12-01 07:45:00,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,United Kingdom
5,13085,2009-12-01 07:45:00,PINK DOUGHNUT TRINKET POT,24,1.65,United Kingdom
6,13085,2009-12-01 07:45:00,SAVE THE PLANET MUG,24,1.25,United Kingdom
7,13085,2009-12-01 07:45:00,FANCY FONT HOME SWEET HOME DOORMAT,10,5.95,United Kingdom
8,13085,2009-12-01 07:46:00,CAT BOWL,12,2.55,United Kingdom
9,13085,2009-12-01 07:46:00,DOG BOWL - CHASING BALL DESIGN,12,3.75,United Kingdom
10,13085,2009-12-01 07:46:00,HEART MEASURING SPOONS LARGE,24,1.65,United Kingdom
11,13085,2009-12-01 07:46:00,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2.55,United Kingdom
12,13078,2009-12-01 09:06:00,DOOR MAT BLACK FLOCK,10,5.95,United Kingdom
13,13078,2009-12-01 09:06:00,LOVE BUILDING BLOCK WORD,18,5.45,United Kingdom
14,13078,2009-12-01 09:06:00,HOME BUILDING BLOCK WORD,3,5.95,United Kingdom
15,13078,2009-12-01 09:06:00,ASSORTED COLOUR BIRD ORNAMENT,16,1.69,United Kingdom
16,13078,2009-12-01 09:06:00,PEACE WOODEN BLOCK LETTERS,3,6.95,United Kingdom
17,13078,2009-12-01 09:06:00,CHRISTMAS CRAFT WHITE FAIRY,12,1.45,United Kingdom
18,13078,2009-12-01 09:06:00,HEART IVORY TRELLIS LARGE,12,1.65,United Kingdom
19,13078,2009-12-01 09:06:00,HEART FILIGREE DOVE LARGE,12,1.65,United Kingdom

In [28]:
print('Nb distincts lines :', len(online_retail.index) )
print('Nb different ids (i.e. sequences):', online_retail.Id.nunique() )

Nb lignes distinctes : 525461
Nb id différents (i.e. séquences): 4383

### Transformation of the dataset to have on each line all the products ordered by a customer on a given date (as well as "statistics" on the order):

[customer id, date of order, list of products, total quantity of products, average quantity of products, total cost of the order, average price of products, Country]

In [29]:
online_retail_all_prod = online_retail.groupby(['Id','Date']).agg({ 'Description' : lambda x : ', '.join(x),
                                           'Quantity' : ['sum','mean'],
                                           'Price' : ['sum', 'mean'],
                                           'Country' : 'first'  } )

# online_retail_all_prod['Description'] = '["'+online_retail_all_prod['Description']+'"]'

online_retail_all_prod['Description'] = online_retail_all_prod['Description'].apply( lambda x : x.str.split(', '))

online_retail_all_prod.head(20)

                                                                 Description  \
                                                                    <lambda>
Id    Date
12346 2009-12-14 08:34:00                          [This is a test product.]
      2009-12-14 11:00:00                          [This is a test product.]
      2009-12-14 11:02:00                          [This is a test product.]
      2009-12-18 10:47:00                          [This is a test product.]
      2009-12-18 10:55:00                          [This is a test product.]
      2010-01-04 09:24:00                          [This is a test product.]
      2010-01-04 09:53:00                          [This is a test product.]
      2010-01-14 13:50:00                          [This is a test product.]
      2010-01-22 13:30:00                          [This is a test product.]
      2010-01-26 17:27:00              [Adjustment by john on 26/01/2010 17]
      2010-03-02 13:08:00  [RED SPOTTY CHILDS UMBRELLA, EDWARDIAN PARASOL...
      2010-06-28 13:53:00  [DOORMAT SPOTTY HOME SWEET HOME, DOORMAT WELCO...
      2010-06-30 11:22:00  [Manual, Manual, Manual, Manual, Manual, Manua...
      2010-10-04 09:54:00                                         [Discount]
      2010-10-04 16:33:00                          [This is a test product.]
12347 2010-10-31 14:20:00  [PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...
      2010-12-07 14:57:00  [BLACK CANDELABRA T-LIGHT HOLDER, AIRLINE BAG ...
12348 2010-09-27 14:59:00  [PACK OF 72 SKULL CAKE CASES, 60 TEATIME FAIRY...
12349 2009-12-04 12:49:00  [TEA CUP AND SAUCER RETRO SPOT, SET/5 RED SPOT...
      2010-04-29 13:20:00  [PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...

                          Quantity              Price            \
                               sum       mean     sum      mean
Id    Date
12346 2009-12-14 08:34:00       10  10.000000    4.50    4.5000
      2009-12-14 11:00:00        5   5.000000    4.50    4.5000
      2009-12-14 11:02:00        5   5.000000    4.50    4.5000
      2009-12-18 10:47:00        5   5.000000    4.50    4.5000
      2009-12-18 10:55:00        1   1.000000    1.00    1.0000
      2010-01-04 09:24:00        5   5.000000    4.50    4.5000
      2010-01-04 09:53:00        5   5.000000    4.50    4.5000
      2010-01-14 13:50:00        5   5.000000    4.50    4.5000
      2010-01-22 13:30:00        5   5.000000    4.50    4.5000
      2010-01-26 17:27:00       -1  -1.000000  103.50  103.5000
      2010-03-02 13:08:00        5   1.000000   27.05    5.4100
      2010-06-28 13:53:00       19   1.000000  142.31    7.4900
      2010-06-30 11:22:00      -15  -1.500000  263.00   26.3000
      2010-10-04 09:54:00       -1  -1.000000    1.00    1.0000
      2010-10-04 16:33:00       -1  -1.000000    4.50    4.5000
12347 2010-10-31 14:20:00      509  12.725000   73.36    1.8340
      2010-12-07 14:57:00      319  10.290323   89.59    2.8900
12348 2010-09-27 14:59:00      373  18.650000   14.39    0.7195
12349 2009-12-04 12:49:00       -5  -1.000000   24.15    4.8300
      2010-04-29 13:20:00      473  10.282609  194.58    4.2300

                                  Country
                                    first
Id    Date
12346 2009-12-14 08:34:00  United Kingdom
      2009-12-14 11:00:00  United Kingdom
      2009-12-14 11:02:00  United Kingdom
      2009-12-18 10:47:00  United Kingdom
      2009-12-18 10:55:00  United Kingdom
      2010-01-04 09:24:00  United Kingdom
      2010-01-04 09:53:00  United Kingdom
      2010-01-14 13:50:00  United Kingdom
      2010-01-22 13:30:00  United Kingdom
      2010-01-26 17:27:00  United Kingdom
      2010-03-02 13:08:00  United Kingdom
      2010-06-28 13:53:00  United Kingdom
      2010-06-30 11:22:00  United Kingdom
      2010-10-04 09:54:00  United Kingdom
      2010-10-04 16:33:00  United Kingdom
12347 2010-10-31 14:20:00         Iceland
      2010-12-07 14:57:00         Iceland
12348 2010-09-27 14:59:00         Finland
12349 2009-12-04 12:49:00           Italy
      2010-04-29 13:20:00           Italy

Save in CSV format the purchases made by a customer on different dates:

In [39]:
online_retail_all_prod.reset_index().to_csv('../Data/CSV/online_retail_II_all_products.csv', index=False, header=['Id','Date','Products','Sum quantities', 'Avg quantity','Sum prices', 'Avg price', 'Country'], sep=';')

### Transformation of the dataset to have on each row the two main products purchased (according to the total cost, i.e. price x quantity) by a customer on a given date:

[customer id, order date, first product, quantity of first product, first product price, second product, second product quantity, second product price, country]

- Calculation of the total cost of each product reference ordered
- Group by data by Id, Date and sorting by total price
- Filter of the two main products for each order

In [40]:

online_retail['Total Price'] = online_retail.Quantity * online_retail.Price
online_retail_best_prods = online_retail.groupby(['Id','Date'], sort=False).apply( lambda x: x.sort_values(['Total Price'], ascending=False)).reset_index(drop=True)

online_retail_best_prods = online_retail_best_prods.groupby(['Id','Date'], sort=False).head(2)

online_retail_best_prods.head(20)

,Id,Date,Description,Quantity,Price,Country,Total Price
0,13085,2009-12-01 07:45:00,RECORD FRAME 7inch SINGLE SIZE,48,2.10,United Kingdom,100.80
1,13085,2009-12-01 07:45:00,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,United Kingdom,83.40
8,13085,2009-12-01 07:46:00,DOG BOWL - CHASING BALL DESIGN,12,3.75,United Kingdom,45.00
9,13085,2009-12-01 07:46:00,HEART MEASURING SPOONS LARGE,24,1.65,United Kingdom,39.60
12,13078,2009-12-01 09:06:00,SCOTTIE DOG HOT WATER BOTTLE,24,4.25,United Kingdom,102.00
13,13078,2009-12-01 09:06:00,LOVE BUILDING BLOCK WORD,18,5.45,United Kingdom,98.10
31,15362,2009-12-01 09:08:00,WOODEN BOX ADVENT CALENDAR,2,8.95,United Kingdom,17.90
32,15362,2009-12-01 09:08:00,FELTCRAFT DOLL EMILY,6,2.95,United Kingdom,17.70
54,18102,2009-12-01 09:24:00,CHARLIE AND LOLA FIGURES TINS,60,6.40,United Kingdom,384.00
55,18102,2009-12-01 09:24:00,CHARLIE + LOLA BISCUITS TINS,60,6.38,United Kingdom,382.80
71,12682,2009-12-01 09:28:00,POSTAGE,3,18.00,France,54.00
72,12682,2009-12-01 09:28:00,RETRO SPOT TEA SET CERAMIC 11 PC,9,4.95,France,44.55
90,18087,2009-12-01 09:43:00,DOG BOWL - CHASING BALL DESIGN,8,3.75,United Kingdom,30.00
91,18087,2009-12-01 09:43:00,CAT BOWL,8,2.55,United Kingdom,20.40
92,18087,2009-12-01 09:44:00,SCOTTIE DOG HOT WATER BOTTLE,48,4.25,United Kingdom,204.00
93,18087,2009-12-01 09:44:00,RED WOOLLY HOTTIE WHITE HEART.,36,2.95,United Kingdom,106.20
96,13635,2009-12-01 09:46:00,KINGS CHOICE CIGAR BOX MATCHES,48,1.25,United Kingdom,60.00
97,13635,2009-12-01 09:46:00,KINGS CHOICE SMALL TUBE MATCHES,20,1.65,United Kingdom,33.00
119,14110,2009-12-01 09:50:00,RECORD FRAME 7inch SINGLE SIZE,48,2.10,United Kingdom,100.80
120,14110,2009-12-01 09:50:00,VINYL RECORD FRAME SILVER,24,3.39,United Kingdom,81.36

Generation of one line per order with addition of columns for the main products ordered

In [41]:
online_retail_first_prod = online_retail_best_prods.groupby(['Id','Date'], sort=False).nth(0).reset_index()
online_retail_second_prod = online_retail_best_prods.groupby(['Id','Date'], sort=False).nth(1).reset_index()

online_retail_best_prods = online_retail_first_prod.set_index(['Id', 'Date', 'Country']).join( online_retail_second_prod.set_index(['Id', 'Date', 'Country']), lsuffix=' First', rsuffix=' Second')

online_retail_best_prods.head(20)

                                                                Description First  \
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom          RECORD FRAME 7inch SINGLE SIZE
      2009-12-01 07:46:00 United Kingdom           DOG BOWL - CHASING BALL DESIGN
13078 2009-12-01 09:06:00 United Kingdom             SCOTTIE DOG HOT WATER BOTTLE
15362 2009-12-01 09:08:00 United Kingdom              WOODEN BOX ADVENT CALENDAR
18102 2009-12-01 09:24:00 United Kingdom            CHARLIE AND LOLA FIGURES TINS
12682 2009-12-01 09:28:00 France                                          POSTAGE
18087 2009-12-01 09:43:00 United Kingdom           DOG BOWL - CHASING BALL DESIGN
      2009-12-01 09:44:00 United Kingdom             SCOTTIE DOG HOT WATER BOTTLE
13635 2009-12-01 09:46:00 United Kingdom          KINGS CHOICE CIGAR BOX MATCHES
14110 2009-12-01 09:50:00 United Kingdom          RECORD FRAME 7inch SINGLE SIZE
12636 2009-12-01 09:55:00 USA                                             POSTAGE
17519 2009-12-01 09:57:00 United Kingdom  GARLAND - WOODEN  inch HAPPY EASTERinch
13758 2009-12-01 10:06:00 United Kingdom               RED SPOTTY ROUND CAKE TINS
12362 2009-12-01 10:10:00 Belgium                                         POSTAGE
15413 2009-12-01 10:18:00 United Kingdom                         GOLD WINE GOBLET
16321 2009-12-01 10:33:00 Australia                  CREAM FELT EASTER EGG BASKET
      2009-12-01 10:36:00 Australia                      PAPER BUNTING WHITE LACE
17592 2009-12-01 10:44:00 United Kingdom              PINK ENAMEL+GLASS HAIR COMB
16167 2009-12-01 10:46:00 United Kingdom            BOYS ALPHABET IRON ON PATCHES
17865 2009-12-01 10:49:00 United Kingdom           STRAWBERRY CERAMIC TRINKET BOX

                                          Quantity First  Price First  \
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom              48         2.10
      2009-12-01 07:46:00 United Kingdom              12         3.75
13078 2009-12-01 09:06:00 United Kingdom              24         4.25
15362 2009-12-01 09:08:00 United Kingdom               2         8.95
18102 2009-12-01 09:24:00 United Kingdom              60         6.40
12682 2009-12-01 09:28:00 France                       3        18.00
18087 2009-12-01 09:43:00 United Kingdom               8         3.75
      2009-12-01 09:44:00 United Kingdom              48         4.25
13635 2009-12-01 09:46:00 United Kingdom              48         1.25
14110 2009-12-01 09:50:00 United Kingdom              48         2.10
12636 2009-12-01 09:55:00 USA                          1       141.00
17519 2009-12-01 09:57:00 United Kingdom              24         1.25
13758 2009-12-01 10:06:00 United Kingdom              12         8.95
12362 2009-12-01 10:10:00 Belgium                      1       130.00
15413 2009-12-01 10:18:00 United Kingdom              48         4.25
16321 2009-12-01 10:33:00 Australia                   -6         1.65
      2009-12-01 10:36:00 Australia                   12         2.95
17592 2009-12-01 10:44:00 United Kingdom              -3         2.10
16167 2009-12-01 10:46:00 United Kingdom             576         0.21
17865 2009-12-01 10:49:00 United Kingdom              48         1.25

                                          Total Price First  \
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom             100.80
      2009-12-01 07:46:00 United Kingdom              45.00
13078 2009-12-01 09:06:00 United Kingdom             102.00
15362 2009-12-01 09:08:00 United Kingdom              17.90
18102 2009-12-01 09:24:00 United Kingdom             384.00
12682 2009-12-01 09:28:00 France                      54.00
18087 2009-12-01 09:43:00 United Kingdom              30.00
      2009-12-01 09:44:00 United Kingdom             204.00
13635 2009-12-01 09:46:00 United Kingdom              60.00
14110 2009-12-01 09:50:00 United Kingdom             100.80
12636 2009-12-01 09:55:00 USA                        141.00
17519 2009-12-01 09:57:00 United Kingdom              30.00
13758 2009-12-01 10:06:00 United Kingdom             107.40
12362 2009-12-01 10:10:00 Belgium                    130.00
15413 2009-12-01 10:18:00 United Kingdom             204.00
16321 2009-12-01 10:33:00 Australia                   -9.90
      2009-12-01 10:36:00 Australia                   35.40
17592 2009-12-01 10:44:00 United Kingdom              -6.30
16167 2009-12-01 10:46:00 United Kingdom             120.96
17865 2009-12-01 10:49:00 United Kingdom              60.00

                                                           Description Second  \
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom  15CM CHRISTMAS GLASS BALL 20 LIGHTS
      2009-12-01 07:46:00 United Kingdom         HEART MEASURING SPOONS LARGE
13078 2009-12-01 09:06:00 United Kingdom             LOVE BUILDING BLOCK WORD
15362 2009-12-01 09:08:00 United Kingdom                 FELTCRAFT DOLL EMILY
18102 2009-12-01 09:24:00 United Kingdom         CHARLIE + LOLA BISCUITS TINS
12682 2009-12-01 09:28:00 France            RETRO SPOT TEA SET CERAMIC 11 PC
18087 2009-12-01 09:43:00 United Kingdom                            CAT BOWL
      2009-12-01 09:44:00 United Kingdom       RED WOOLLY HOTTIE WHITE HEART.
13635 2009-12-01 09:46:00 United Kingdom      KINGS CHOICE SMALL TUBE MATCHES
14110 2009-12-01 09:50:00 United Kingdom            VINYL RECORD FRAME SILVER
12636 2009-12-01 09:55:00 USA                                             NaN
17519 2009-12-01 09:57:00 United Kingdom             BIRD DECORATION RED SPOT
13758 2009-12-01 10:06:00 United Kingdom     RED HANGING HEART T-LIGHT HOLDER
12362 2009-12-01 10:10:00 Belgium                                         NaN
15413 2009-12-01 10:18:00 United Kingdom                      GOLD WINE GLASS
16321 2009-12-01 10:33:00 Australia                        POTTING SHED TWINE
      2009-12-01 10:36:00 Australia                PAPER CHAIN KIT RETRO SPOT
17592 2009-12-01 10:44:00 United Kingdom        PURPLE ENAMEL+GLASS HAIR COMB
16167 2009-12-01 10:46:00 United Kingdom      GIRLS ALPHABET IRON ON PATCHES
17865 2009-12-01 10:49:00 United Kingdom                   FAIRY CAKE CANDLES

                                          Quantity Second  Price Second  \
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom             12.0          6.95
      2009-12-01 07:46:00 United Kingdom             24.0          1.65
13078 2009-12-01 09:06:00 United Kingdom             18.0          5.45
15362 2009-12-01 09:08:00 United Kingdom              6.0          2.95
18102 2009-12-01 09:24:00 United Kingdom             60.0          6.38
12682 2009-12-01 09:28:00 France                      9.0          4.95
18087 2009-12-01 09:43:00 United Kingdom              8.0          2.55
      2009-12-01 09:44:00 United Kingdom             36.0          2.95
13635 2009-12-01 09:46:00 United Kingdom             20.0          1.65
14110 2009-12-01 09:50:00 United Kingdom             24.0          3.39
12636 2009-12-01 09:55:00 USA                         NaN           NaN
17519 2009-12-01 09:57:00 United Kingdom             24.0          0.85
13758 2009-12-01 10:06:00 United Kingdom             32.0          2.55
12362 2009-12-01 10:10:00 Belgium                     NaN           NaN
15413 2009-12-01 10:18:00 United Kingdom             48.0          3.39
16321 2009-12-01 10:33:00 Australia                  -6.0          2.10
      2009-12-01 10:36:00 Australia                  12.0          2.95
17592 2009-12-01 10:44:00 United Kingdom             -3.0          2.10
16167 2009-12-01 10:46:00 United Kingdom            288.0          0.21
17865 2009-12-01 10:49:00 United Kingdom             27.0          1.49

                                          Total Price Second
Id    Date                Country
13085 2009-12-01 07:45:00 United Kingdom               83.40
      2009-12-01 07:46:00 United Kingdom               39.60
13078 2009-12-01 09:06:00 United Kingdom               98.10
15362 2009-12-01 09:08:00 United Kingdom               17.70
18102 2009-12-01 09:24:00 United Kingdom              382.80
12682 2009-12-01 09:28:00 France                       44.55
18087 2009-12-01 09:43:00 United Kingdom               20.40
      2009-12-01 09:44:00 United Kingdom              106.20
13635 2009-12-01 09:46:00 United Kingdom               33.00
14110 2009-12-01 09:50:00 United Kingdom               81.36
12636 2009-12-01 09:55:00 USA                            NaN
17519 2009-12-01 09:57:00 United Kingdom               20.40
13758 2009-12-01 10:06:00 United Kingdom               81.60
12362 2009-12-01 10:10:00 Belgium                        NaN
15413 2009-12-01 10:18:00 United Kingdom              162.72
16321 2009-12-01 10:33:00 Australia                   -12.60
      2009-12-01 10:36:00 Australia                    35.40
17592 2009-12-01 10:44:00 United Kingdom               -6.30
16167 2009-12-01 10:46:00 United Kingdom               60.48
17865 2009-12-01 10:49:00 United Kingdom               40.23

Save in CSV format the two most important purchases made by a customer on different dates:

In [42]:
online_retail_best_prods.reset_index().to_csv('../Data/CSV/online_retail_II_best_products.csv', index=False, sep=';')